# Generated by Django 4.1.7 on 2023-06-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "INACTIVE"), (1, "ACTIVE"), (2, "OTHER")],
                        default=1,
                        verbose_name="Holati",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="yaratilgan vaqt"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="tahrirlangan vaqt"
                    ),
                ),
                (
                    "question",
                    models.CharField(max_length=250, unique=True, verbose_name="Savol"),
                ),
                (
                    "answer",
                    models.CharField(max_length=250, verbose_name="To'g'ri javob"),
                ),
                (
                    "option1",
                    models.CharField(max_length=250, verbose_name="Xato javob"),
                ),
                (
                    "option2",
                    models.CharField(max_length=250, verbose_name="Xato javob"),
                ),
                (
                    "option3",
                    models.CharField(max_length=250, verbose_name="Xato javob"),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "abstract": False,
            },
        ),
    ]
