# Generated by Django 4.1.7 on 2023-06-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_answer_option_question_delete_test_option_question_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Letters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "INACTIVE"), (1, "ACTIVE"), (2, "OTHER")],
                        default=1,
                        verbose_name="Holati",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="yaratilgan vaqt"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="tahrirlangan vaqt"
                    ),
                ),
                (
                    "letter",
                    models.CharField(
                        choices=[
                            ("a", "A"),
                            ("b", "B"),
                            ("c", "C"),
                            ("d", "D"),
                            ("e", "E"),
                            ("f", "F"),
                            ("g", "G"),
                            ("h", "H"),
                        ],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="answer",
            options={"verbose_name": "Javob", "verbose_name_plural": "3.Javoblar"},
        ),
        migrations.AlterModelOptions(
            name="option",
            options={
                "ordering": ["question", "text"],
                "verbose_name": "Variant",
                "verbose_name_plural": "2.Variantlar",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["text"],
                "verbose_name": "Savol",
                "verbose_name_plural": "1.Savollar",
            },
        ),
    ]
